# Generated by Django 3.2.13 on 2023-03-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rc_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('points',), 'verbose_name_plural': 'Participantes'},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
    ]
